### ISSUE TITLE
ASCII codec is too limiting

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/lmk#1]
lmk is easily tripped up by non-ascii output, e.g. the quotation marks in this error message:

```
$ lmk -e 'wget http://www.pip-db.asdasdorg -O /dev/null'
--2017-05-30 15:05:53--  http://www.pip-db.asdasdorg/
Resolving www.pip-db.asdasdorg (www.pip-db.asdasdorg)... failed: Name or service not known.
wget: unable to resolve host address ‘www.pip-db.asdasdorg’
Traceback (most recent call last):
  File "/usr/local/bin/lmk", line 749, in <module>
    main()
  File "/usr/local/bin/lmk", line 742, in main
    sys.exit(run_subprocess(args.command, only_errors=args.only_errors))
  File "/usr/local/bin/lmk", line 723, in run_subprocess
    date_started=date_started, date_ended=date_ended)
  File "/usr/local/bin/lmk", line 654, in let_me_know
    date_started=date_started, date_ended=date_ended)
  File "/usr/local/bin/lmk", line 554, in build_html_message_body
    """.format(**vars())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 271: ordinal not in range(128)
```

**Comment by ChrisCummins** [comment]
fixed
